name: "makecmap_cmap2bed"
description: converted a id converted bionano cmap to a bed file
keywords:
  - cmap
tools:
  - "cmap2bed":
      description: "converted a id converted bionano cmap to a bed file and sort it in numerial order"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - cmap:
      type: file
      description: cmap file
      pattern: "*.{cmap}"
  - enzyme:
      type: value
      description: bionnano restriction enzyme name

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bedfile:
      type: file
      description: converted bed file
      pattern: "*.bed"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@yumisims"
