name: "selfcomp_splitfasta"
description: Script to split fasta into 500kb
keywords:
  - fasta
  - split
tools:
  - "selfcomp":
      licence: "sanger"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - split_fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"
  - split_agp:
      type: file
      description: File describing assembly of a larger sequence object from smaller ones.
      pattern: "*.{agp}"
authors:
  - "@weaglesBio"
